version: '3.1'

services:

  api:
    build: ./api
    image: api:latest
    ports:
      - 8081:80
    depends_on:
      - database
  
  database:
    build: ./database
    image: mssql:latest
    environment:
      - ACCEPT_EULA=Y 
      - sa_password=P@ssw0rd
